### The purpose of this docker file is to show how to mount 
### a local folder and generate a file with tools installed
### in the container image
### Usage: docker build -f Dockerfile.generator -t docker-gen:latest . && docker run -it -v $(pwd)/gen-folder:/data docker-gen:latest

FROM alpine:latest

VOLUME [ "/data" ]

RUN apk update && apk add jq

RUN jq --help

# Write a testing file
CMD ["/bin/sh", "-c", "echo '{\"a\": \"This is a test\"}' | jq --raw-output '.a' > /data/gen-file.txt"]